name: Cashcraft-Utils
version: 1.0.0
author: [Movies22, JackGAttack4]
main: com.cashcraft.utils.Main
description: Cashcraft Utilities plugin.
api-version: 1.19
commands:
    sign:
        description: Edits a sign
        usage: /sign [colour/set/clear] [1/2/3/4/all] [text]
        aliases: [editsign]
        permission: cashcraft.sign
    create:
        description: Create lifts (and more soon)
        usage: /create [lift]
        permission: cashcraft.lift
    invisitem:
        description: Get invisible Item Frames
        usage: /invisitem [glow]
        permission: cashcraft.item
        