name: Cashcraft-Utils
version: 1630
author: [Movies22, JackGAttack4]
main: com.cashcraft.utils.Main
description: Cashcraft Utilities plugin.
api-version: 1.19
commands:
    sign:
        description: Edits a sign
        usage: /sign [colour/set/clear/glow] [1/2/3/4/sign] [text]
        aliases: [editsign]
        permission: cashcraft.sign
    create:
        description: Create lifts (and more soon)
        usage: /create [lift]
        permission: cashcraft.create
    invisitem:
        description: Get invisible Item Frames
        usage: /invisitem <glow>
        permission: cashcraft.item
    metro:
        description: Teleports to a metro station
        usage: /metro [station/list]
        permission: cashcraft.metro
    createmetro:
        description: Create a metro station
        usage: /createmetro [station] [code] [w:WARP/h:HOME/t:TC NODE] <Position>
        aliases: [cm]
        permission: cashcraft.metro.create
    delmetro:
        description: Deletes a metro station
        usage: /delmetro [code/station] <Position>
        aliases: [deletemetro, rmetro]
        permission: cashcraft.metro.delete 
    maintenance:
        description: Starts/Stops a server maintenance
        usage: /maintenance [on/off] <reason>
        permission: cashcraft.maintenance.use